### ISSUE TITLE
Is it possible to rewrite this to change the syntax of the import?

### ISSUE THREAD

**Issue by Evertt** [locoslab/vue-typescript-import-dts#2]
I really know next to nothing about typescript to be honest, so I apologize if the answer to this question "of course not, duh".

Anyhow, when one installs this package, one can import `.vue` files like so:

```javascript
import Child = require('./child.vue')
// or
import * as Child from './child.vue'
```

But honestly, I much prefer this syntax:

```javascript
import Child from './child.vue'
```

Is it possible to rewrite this package so that that syntax is possible?

**Comment by locobert** [comment]
Changed in 3.0

**Comment by Evertt** [comment]
You haven't tagged a new version yet though. :-)
