### ISSUE TITLE
index.ts is not published

### ISSUE THREAD

**Issue by MeirionHughes** [locoslab/vue-typescript-import-dts#4]
index.ts is not in the npm package distribution `@3.1.0`, 

webpack reports it cannot find the import without it.

**Comment by MeirionHughes** [comment]
![image](https://user-images.githubusercontent.com/3584509/28660235-2088effc-72aa-11e7-8ec7-41f929782a3c.png)

@locobert Sorry to nag; but could you publish with the index.ts file please - importing this package results in an error without it.

**Comment by locobert** [comment]
Updated to 3.1.1. Please let me know if the issue is resolved.

**Comment by MeirionHughes** [comment]
Thank you; tsc is happy with`import "vue-typescript-import-dts";`
